import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import DarkThemeProvider from '@/components/DarkThemeProvider';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My Localhost Title',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DarkThemeProvider>
          <>
            {children}
          </>
        </DarkThemeProvider>
      </body>
    </html>
  )
}
